### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by gowthaman-i2i** [atom/spell-check#130]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Microsoft Windows 10 Home
**Thrown From**: [spell-check](https://github.com/atom/spell-check) package, v0.67.0

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\spell-check\lib\main.js:43

TypeError: Cannot read property 'id' of undefined
    at Object.module.exports.toggle (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\spell-check\lib\main.js:43:54)
    at atom-workspace.commandSubscription.atom.commands.add.spell-check:toggle (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\spell-check\lib\main.js:13:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\src\atom-environment.js:1100:28)
    at EventEmitter.outerCallback (C:\Users\Gouthaman\AppData\Local\atom\app-1.7.2\resources\app.asar\src\application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -1:18.1.0 application:add-project-folder (ul.list-inline.tab-bar.inset-panel)
     -0:52.3.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:49.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:45.3.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:42 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:22.9.0 tree-view:add-folder (span.name.icon.icon-file-directory)
     -0:19.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:18.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:14.2.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:05.7.0 spell-check:toggle (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "angularjs-styleguide-snippets-es6"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs-styleguide-snippets, v0.7.3

# Dev
No dev packages
```

**Comment by roccosportal** [comment]
I can not reproduce the error with a freshly installed atom v1.7.2 and spell-check v0.67.0.

**Comment by maptracker** [comment]
I had the same error, once, with similar stack. I think this might have to do with cursor focus? I am using the Markdown preview package, and if I have focus on the preview pane I get the error. If I return focus to the markdown document, the toggle seems to work fine. I presume spell check is dormant for static documents (like previews), and that that's the issue?

Atom 1.7.3
Ubuntu  14.04

```
/usr/share/atom/resources/app.asar/node_modules/spell-check/lib/main.js:43
Hide Stack Trace
TypeError: Cannot read property 'id' of undefined
    at Object.module.exports.toggle (/usr/share/atom/resources/app.asar/node_modules/spell-check/lib/main.js:43:54)
    at atom-workspace.commandSubscription.atom.commands.add.spell-check:toggle (/usr/share/atom/resources/app.asar/node_modules/spell-check/lib/main.js:13:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by maptracker** [comment]
For reproducing (if you're not using Markdown), I just tried toggling spell check while focus was on the Core Settings page, and got the same error.

**Comment by roccosportal** [comment]
I added a simple check for undefined. That should fix it now.

**Comment by steelbrain** [comment]
I got this bug when I toggled spell check without a text editor tab focused

**Comment by aakhmetz** [comment]
the same for me
