### ISSUE TITLE
Crashes continually with .sh file extension 

### ISSUE THREAD

**Issue by Eadword** [atom/spell-check#147]
Typing anything into an bash script seems to be throwing errors left and right. And when I say anything, I mean type one character and it throws an error, type another, another error, and so on.

The file extension is .sh and that seems to be the trigger for problems.

```
File 0Project 0No Issuesdata/email-templates/compile.sh1:1
LFUTF-8Shell Scriptmaster
Error: spawn shellcheck ENOENT
Error: spawn shellcheck ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

```
Error: spawn shellcheck ENOENT
Error: spawn shellcheck ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

**Comment by cocoaway** [comment]
Same problem, disabled linter-shellcheck from Settings-->Packages.
Now no crash.

**Comment by thijsbraem** [comment]
You need to install the ShellCheck (in Fedora, other distros will likely have another name) package.

**Comment by twang2218** [comment]
For Ubuntu or Debian, you need install `shellcheck` by command:

```bash
$ sudo apt-get install shellcheck
```
