### ISSUE TITLE
Uncaught TypeError: Cannot read property 'active' of undefined

### ISSUE THREAD

**Issue by andmos** [atom/spell-check#210]
Worked perfectly before I upgraded to `1.17.0 x64`. 
To reproduce, use same configuration as listed below (I guess) and try opening a markdown file `someFile.md`. Normally the spell-checker package kicks in right away, but `spell-check:toggle` was needed now and threw this error. 

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [spell-check](https://github.com/atom/spell-check) package 0.71.4

### Stack Trace

Uncaught TypeError: Cannot read property 'active' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/spell-check/lib/main.js:180

TypeError: Cannot read property 'active' of undefined
    at Object.toggle (/Applications/Atom.app/Contents/Resources/app/node_modules/spell-check/lib/main.js:180:1)
    at atom-workspace.commandSubscription.atom.commands.add.spell-check:toggle (/Applications/Atom.app/Contents/Resources/app/node_modules/spell-check/lib/main.js:66:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:106:1)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:313:1)
    at HTMLDivElement.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:81:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -0:03.5.0 command-palette:toggle (input.hidden-input)
     -0:01.7.0 core:confirm (input.hidden-input)
     -0:01.7.0 spell-check:toggle (input.hidden-input)
```

### Non-Core Packages

```
ansible-vault 0.5.2 
asciidoc-preview 2.10.1 
busy-signal 1.4.1 
color-picker 2.2.5 
file-icons 2.1.6 
intentions 1.1.2 
ionide-paket 2.2.6 
language-ansible 0.2.1 
language-asciidoc 1.10.0 
language-docker 1.1.7 
language-latex 1.0.0 
language-powershell 4.0.0 
language-terraform 0.8.1 
latex 0.43.0 
latex-autocomplete 1.0.0 
linter 2.1.4 
linter-ui-default 1.5.4 
minimap 4.28.2 
omnisharp-atom 0.31.2 
pretty-json 1.6.3 
sort-lines 0.14.0 
svg-preview 0.11.0 
unity-ui 2.1.10 
visual-studio-dark-syntax 0.1.0 
VisualStudio 0.1.3 
```

**Comment by rsese** [comment]
I think this is basically the same error based on the stack trace isn't exactly, copied from @borishere in https://github.com/atom/atom/issues/16403.

---

[Enter steps to reproduce:]

1. Open big file in Atom

I also use a script in order to turn off annoying spell check when opening a file...
```
atom.workspace.observeTextEditors (editor) ->
  setTimeout ->
    atom.commands.dispatch atom.views.getView(editor), 'spell-check:toggle'
  , 0 if editor.element.spellcheck
```

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise N 2015 LTSB
**Thrown From**: Atom Core


### Stack Trace

Uncaught TypeError: Cannot read property 'active' of undefined

```
At C:\Users\user\AppData\Local\atom\app-1.23.1\resources\app\node_modules\spell-check\lib\main.js:164

TypeError: Cannot read property 'active' of undefined
    at Object.toggle (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/spell-check/lib/main.js:164:42)
    at HTMLElement.subs.add.atom.commands.add.spell-check:toggle (~/AppData/Local/atom/app-1.23.1/resources/app/node_modules/spell-check/lib/main.js:69:32)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.1/resources/app/src/command-registry.js:273:23)
    at ~/.atom/init.coffee:17:19
```

### Commands

```
     -0:22 spell-check:toggle (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-live-server 2.2.0 
atom-unsaved-changes 0.4.0 
autocomplete-paths 2.12.1 
block-comment 0.4.3 
build 0.69.0 
build-sass 0.11.0 
busy 0.7.0 
busy-signal 1.4.3 
color-picker 2.2.5 
console-log 1.10.0 
ctrl-dir-scroll 0.2.5 
cursor-blink-interval 0.3.1 
fake-image-snippets 1.1.0 
file-icons 2.1.15 
file-watcher 1.2.6 
filesize 3.0.0 
fonts 3.0.3 
goto-definition 1.3.4 
highlight-selected 0.13.1 
inc 0.0.4 
intentions 1.1.5 
jquery-snippets 11.0.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-htmlhint 1.4.0 
linter-jsonlint 1.3.0 
linter-markdown 5.2.0 
linter-stylelint 4.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
minimap-split-diff 0.3.7 
open-in-browser 0.5.2 
pigments 0.40.2 
project-manager 3.3.5 
random 1.4.1 
split-diff 1.5.1 
sync-settings 0.8.3 
toggle-quotes 1.1.0 
tree-view-autoresize 2.3.0 
```

**Comment by rsese** [comment]
A few questions @borishere:

* How big is the file you opened?  
* Can you reproduce the error consistently?
* If you remove that code to disable spell-check from your init file, can you reproduce?
*

**Comment by Arcanemagus** [comment]
Here's a stack trace from https://github.com/atom/atom/commit/4814a8e3cbacf3af0ea0a4195a9c1d77595e1444, which is pulling in [v0.74.1](https://github.com/atom/spell-check/tree/v0.74.1):
```
Uncaught TypeError: Cannot read property 'active' of undefined
    at Object.toggle (file:///C:/temp/atom/out/app/node_modules/spell-check/lib/main.coffee:153:34)
    at HTMLElement.subs.add.atom.commands.add.spell-check:toggle (file:///C:/temp/atom/out/app/node_modules/spell-check/lib/main.coffee:57:35)
    at CommandRegistry.handleCommandEvent (C:\temp\atom\src\command-registry.js:384:43)
    at Object.didConfirmSelection (file:///C:/temp/atom/out/app/node_modules/command-palette/lib/command-palette-view.js:77:28)
    at SelectListView.confirmSelection (C:\temp\atom\node_modules\atom-select-list\src\select-list-view.js:400:20)
    at HTMLDivElement.core:confirm (C:\temp\atom\node_modules\atom-select-list\src\select-list-view.js:105:14)
    at CommandRegistry.handleCommandEvent (C:\temp\atom\src\command-registry.js:384:43)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\temp\atom\node_modules\atom-keymap\lib\keymap-manager.js:617:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\temp\atom\node_modules\atom-keymap\lib\keymap-manager.js:408:22)
    at WindowEventHandler.handleDocumentKeyEvent (C:\temp\atom\src\window-event-handler.js:110:34)
```

I was editing a ~4.5 MiB file, this seems to be due to `spellCheckViews` not having an index for that `editorId` at all, which is because editors that are larger than `LARGE_FILE_SIZE` are ignored when observing the editors.
