### ISSUE TITLE
Uncaught TypeError: Cannot read property 'send' of null

### ISSUE THREAD

**Issue by masonlr** [atom/spell-check#218]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [spell-check](https://github.com/atom/spell-check) package 0.71.4

### Stack Trace

Uncaught TypeError: Cannot read property 'send' of null

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/spell-check/lib/main.js:155

TypeError: Cannot read property 'send' of null
    at Object.sendGlobalArgs (/Applications/Atom.app/Contents/Resources/app/node_modules/spell-check/lib/main.js:155:29)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/spell-check/lib/main.js:61:27
    at /Applications/Atom.app/Contents/Resources/app/src/config.js:644:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:835:35)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:621:25)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:236:20)
    at Object.applySettings (/packages/sync-settings/lib/sync-settings.coffee:308:21)
    at Object.applySettings (/packages/sync-settings/lib/sync-settings.coffee:305:10)
    at /packages/sync-settings/lib/sync-settings.coffee:231:14
    at /packages/sync-settings/node_modules/github/lib/index.js:819:17
    at callCallback (/packages/sync-settings/node_modules/github/lib/index.js:667:17)
    at /packages/sync-settings/node_modules/github/lib/index.js:726:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -9:21 settings-view:open (input.hidden-input)
     -9:12.5.0 core:confirm (input.hidden-input)
     -6:34.5.0 core:paste (input.hidden-input)
     -1:39.6.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:39.2.0 core:backspace (input.hidden-input)
  2x -0:36.6.0 core:paste (input.hidden-input)
     -0:28.5.0 command-palette:toggle (input.hidden-input)
  2x -0:27.1.0 core:move-down (input.hidden-input)
     -0:26.2.0 core:move-up (input.hidden-input)
  2x -0:25.6.0 core:move-down (input.hidden-input)
     -0:22.5.0 core:confirm (input.hidden-input)
     -0:22.5.0 sync-settings:view-backup (input.hidden-input)
     -0:12 command-palette:toggle (input.hidden-input)
  2x -0:10.8.0 core:move-down (input.hidden-input)
     -0:09.4.0 core:confirm (input.hidden-input)
     -0:09.4.0 sync-settings:restore (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
autocomplete-paths 1.0.5 
copy-path 0.4.1 
sync-settings 0.8.2 
```

**Comment by 50Wliu** [comment]
:wave: @masonlr what were you doing when this error occurred?

**Comment by masonlr** [comment]
I was running `sync-settings-restore`. I have the sync-settings gist data if you need that. Let me know.

**Comment by ethernal** [comment]
You can invoke this error also by:

1.  Setup a proper path to dictionaries (on Windows absolute path is required [which is PITA TBH] ) 
2.  Setup the "wrong" (relative) path to dictionaries.
3.  Disable the package.
4. Focus dictionaries field and press Ctrl-z to undo the changes.

Error occurs, but possibly due to different reasons.

**Comment by AlamyLiu** [comment]
Similar problem, reproduced steps:

- Packages > Spell Check > Settings (spell-check 0.71.4)
- With the package Enabled, Toggle [Use Locales].

Toggle [Use Locales] with package Disabled won't trigger the problem.
In my case: I have "en-US" in the Locales field. But it still triggers the problem when the Locales field is empty.

BTW, I added "source.python" to the Grammars field. Should not be the cause, but FYI.
