### ISSUE TITLE
npm command problems

### ISSUE THREAD

**Issue by RanaAbdullah2017** [atom/spell-check#229]
TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)
I have this problem when I write any npm command in command windows, can any one help me to solve this problem, I tried to solve it but failed to find a solution...

**Comment by 50Wliu** [comment]
Thanks for reaching out!  Unfortunately, it doesn't look like this has anything to do with Atom.  You may have better help asking at the [npm/npm](https://github.com/npm/npm) repository.
