### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by dableze** [atom/spell-check#371]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.5
**Thrown From**: [spell-check](https://github.com/atom/spell-check) package 0.77.1

### Stack Trace

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```
At /private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app.asar/node_modules/atom-pathspec/index.js:30

TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.exports.getPath (/app.asar/node_modules/atom-pathspec/index.js:30:33)
    at LocaleChecker.deferredInit (/app.asar/node_modules/spell-check/lib/locale-checker.js:108:39)
    at LocaleChecker.check (/app.asar/node_modules/spell-check/lib/locale-checker.js:70:14)
    at SpellCheckerManager.check (/private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:11:965712)
    at Function.startNextJob (/private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:14:971342)
    at SpellCheckTask.start (/private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:14:970750)
    at SpellCheckView.updateMisspellings (/private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:11:961755)
    at /private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:11:961183
    at Function.simpleDispatch (/private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1187631)
    at /private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:11:54435
    at Function.simpleDispatch (/private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1187631)
    at TextMateLanguageMode.markTokenizationComplete (/private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:11:557673)
    at TextMateLanguageMode.tokenizeNextChunk (/private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:11:557585)
    at /private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:11:556987
    at /private/var/folders/lz/mp7gnbms4knfjx9bzv39nt2m0000gn/T/AppTranslocation/649620AB-6448-41A8-8D87-0A69F1F616B1/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1173371
```

### Commands

```
     -6:54.1.0 application:reopen-project (div#add-projects-view.)
     -6:40.8.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -5:39.1.0 core:select-all (input.hidden-input)
     -4:05.2.0 core:save (input.hidden-input)
     -4:00.9.0 editor:copy-path (input.hidden-input)
     -2:36.5.0 editor:newline (input.hidden-input)
     -2:33 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -2:21.3.0 core:backspace (input.hidden-input)
     -1:55.7.0 core:save (input.hidden-input)
     -0:54 grammar-selector:show (atom-text-editor.editor)
     -0:51.2.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -0:49 encoding-selector:show (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
Hydrogen 2.16.3 
```

**Comment by dmoonfire** [comment]
Could you tell me what settings you have on the spell-check settings? Looking at this, I'm getting a null where I don't expect to see one.
