### ISSUE TITLE
Does not work in 0.190.0

### ISSUE THREAD

**Issue by KonstantinosX** [atom/spell-check#55]
If I open atom in safe mode (atom --safe), then it works, otherwise I get this  error message in  the Developer tools log: 

Module version mismatch. Expected 43, got 41. ATOM_SHELL_ASAR.js:118
        return old.apply(this, arguments);
                   ^
Error: Module version mismatch. Expected 43, got 41.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/kostasx/.atom/packages/spell- check/node_modules/spellchecker/lib/spellchecker.js:2:16)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)

**Comment by KonstantinosX** [comment]
Fixed the issue by uninstalling spell-check ```apm uninstall spell-check``` . Don't know how this happened but apparently I had installed it again, regardless of it being included in the standard packages, and the other installation was conflicting with the one in the standard packages. 

Perhaps something to look into.
